version: '3.9'
services:
  neo4j:
    container_name: persona-graph-neo4j
    image: neo4j:latest
    restart: always
    environment:
      NEO4J_AUTH: neo4j/passwordz
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j-data:/data
  
  app:
    container_name: persona-graph-app
    build: .
    volumes:
      - ./persona_graph:/app/persona_graph
      - ./app_server:/app/app_server
      - ./tests:/app/tests
    env_file:
      - .env
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=passwordz
    ports:
      - "8000:8000"
    depends_on:
      - neo4j